---Módulo with Global environment variables
local envs = {}

local util = require('app/shared/utils/util')

--- Application envs
envs.APP_NAME = 'fellow'

--- External services
envs.TRACKER_URL = 'http://54.161.255.71:8000/__health' -- without final "/"
envs.PRIMETIME_URL = 'http://54.161.255.71:4005' -- without final "/"

--- Envs generated by builder (build time)
envs.APP_VERSION = '0.5.12'
envs.APP_NAME_VERSION = envs.APP_NAME..'-'..envs.APP_VERSION
envs.CHANNEL_WORKSPACE_ID = 'ebe55c6d-3faa-4d23-8f7f-df897b1bddab'
envs.ENVIRONMENT = 'DEVELOPMENT'
envs.DEBUG_MODE = util.parseStringBoolOrError('true')
envs.EVENT_DEBUG_MODE = util.parseStringBoolOrError('false')

return envs